<?php
// vim: set filetype=php expandtab tabstop=2 shiftwidth=2 autoindent smartindent:

/**
 * Resources:
 * - http://yetanotherprogrammingblog.com/content/drupal-7-external-authentication-sample-code
 */

require_once('RestAuth/restauth.php');

$_restauth_connection;


function get_restauth_connection() {
    global $_restauth_connection;
    if (is_null($_restauth_connection)) {
        $_restauth_connection = new RestAuthConnection(
            'http://[::1]:8000',
            'example.com',
            'nopass'
        );
    }
    return $_restauth_connection;
}


/**
 * Implement hook_help() to display a small help message if somebody clicks the "Help" link on the modules list.
 */
function restauth_help( $path, $arg ) {
  switch ( $path ) {
    case 'admin/help#extauth': {
      return( '<p>' . t('RestAuth authentication.') . '</p>' );
    }
  }
}

/**
 * Implement hook_form_alter() to change the behaviour of the login form.
 *
 * Login validators are set in the user_login_default_validators() function in user.module.
 * They are normally set to array('user_login_name_validate',
 * 'user_login_authenticate_validate', 'user_login_final_validate').
 * We simply replace 'user_login_authenticate_validate' with 'extauth_login_validate'.
 */
function restauth_form_user_login_alter(&$form, $form_state) {
  $form['#validate'] = array('user_login_name_validate', 'restauth_login_validate', 'user_login_final_validate');
}
function restauth_form_user_login_block_alter(&$form, $form_state) {
  $form['#validate'] = array('user_login_name_validate', 'restauth_login_validate', 'user_login_final_validate');
}

function restauth_login_validate($form, &$form_state) {
  global $user;
  $username = $form_stage['values']['name'];
  $restauth_conn = restauth_connection();
  $restauth_user = new RestAuthUser($restauth_conn, $username);

  if ($restauth_user->verifyPassword($form_stage['values']['pass'])) {
    user_external_login_register( $username, 'extauth' );
    $form_state['uid'] = $user->uid;
  } else {
    die('wrong password!');
  }
}
